# Create a new Release.

# This workflow will update tag/version, build and push a Docker container to the container registry.
# If configured to auto-deploy, it will also deploy the new version to the cluster.
name: Release

on: 
  push:
    branches:
      - main
env:
  VERSION_FILE: VERSION
jobs:

  update_version_tag:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.update_version.outputs.TAG }}
    permissions:
      contents: 'write'
      id-token: 'write'      
    steps:
      - uses: actions/checkout@v3
      - id: update_version
        name: Read VERSION file and bump minor version
        run: |
          TAG=$(cat $VERSION_FILE | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)
          echo "New version is $TAG"
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
          echo "TAG=$TAG" >> "$GITHUB_ENV"
      - name: Commit & push new version
        run: |
          TAG=${{env.TAG}}
          git config --global user.name 'Github Actions'
          git config --global user.email 'CI@users.noreply.github.com'
          echo $TAG > $VERSION_FILE
          git add $VERSION_FILE
          git commit -m "Update VERSION to --> $TAG [skip ci]"
          git push origin main
  
  build:
    uses: ./.github/workflows/build_image.yml
    needs: update_version_tag
    permissions:
      contents: 'write'
      id-token: 'write'
    with:
      tag: ${{needs.update_version_tag.outputs.TAG}}
    secrets: inherit

  # Deploy the new version to the cluster
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: [update_version_tag, build]
    with:
      tag: ${{needs.update_version_tag.outputs.TAG}}
      overlay: dev
      cluster_name: koala-demo-cluster
      cluster_zone: me-west1-a
    secrets: inherit